// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trentinotrack.proto

package eu.trentorise.smartcampus.service.trentinotrack.data.message;

public final class Trentinotrack {
  private Trentinotrack() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BikeTrackOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string id = 1;
    boolean hasId();
    String getId();
    
    // required string about = 2;
    boolean hasAbout();
    String getAbout();
    
    // optional string label = 3;
    boolean hasLabel();
    String getLabel();
    
    // optional string length = 4;
    boolean hasLength();
    String getLength();
    
    // optional string polyline = 5;
    boolean hasPolyline();
    String getPolyline();
  }
  public static final class BikeTrack extends
      com.google.protobuf.GeneratedMessage
      implements BikeTrackOrBuilder {
    // Use BikeTrack.newBuilder() to construct.
    private BikeTrack(Builder builder) {
      super(builder);
    }
    private BikeTrack(boolean noInit) {}
    
    private static final BikeTrack defaultInstance;
    public static BikeTrack getDefaultInstance() {
      return defaultInstance;
    }
    
    public BikeTrack getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_BikeTrack_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_BikeTrack_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string about = 2;
    public static final int ABOUT_FIELD_NUMBER = 2;
    private java.lang.Object about_;
    public boolean hasAbout() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getAbout() {
      java.lang.Object ref = about_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          about_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAboutBytes() {
      java.lang.Object ref = about_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        about_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string label = 3;
    public static final int LABEL_FIELD_NUMBER = 3;
    private java.lang.Object label_;
    public boolean hasLabel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          label_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string length = 4;
    public static final int LENGTH_FIELD_NUMBER = 4;
    private java.lang.Object length_;
    public boolean hasLength() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getLength() {
      java.lang.Object ref = length_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          length_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLengthBytes() {
      java.lang.Object ref = length_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        length_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string polyline = 5;
    public static final int POLYLINE_FIELD_NUMBER = 5;
    private java.lang.Object polyline_;
    public boolean hasPolyline() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getPolyline() {
      java.lang.Object ref = polyline_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          polyline_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPolylineBytes() {
      java.lang.Object ref = polyline_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        polyline_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = "";
      about_ = "";
      label_ = "";
      length_ = "";
      polyline_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAbout()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAboutBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLabelBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getLengthBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getPolylineBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAboutBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLabelBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getLengthBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getPolylineBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_BikeTrack_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_BikeTrack_fieldAccessorTable;
      }
      
      // Construct using eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        about_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        label_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        length_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        polyline_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack.getDescriptor();
      }
      
      public eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack getDefaultInstanceForType() {
        return eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack.getDefaultInstance();
      }
      
      public eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack build() {
        eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack buildPartial() {
        eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack result = new eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.about_ = about_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.label_ = label_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.length_ = length_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.polyline_ = polyline_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack) {
          return mergeFrom((eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack other) {
        if (other == eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasAbout()) {
          setAbout(other.getAbout());
        }
        if (other.hasLabel()) {
          setLabel(other.getLabel());
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        if (other.hasPolyline()) {
          setPolyline(other.getPolyline());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasAbout()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              about_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              label_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              length_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              polyline_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // required string about = 2;
      private java.lang.Object about_ = "";
      public boolean hasAbout() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getAbout() {
        java.lang.Object ref = about_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          about_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAbout(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        about_ = value;
        onChanged();
        return this;
      }
      public Builder clearAbout() {
        bitField0_ = (bitField0_ & ~0x00000002);
        about_ = getDefaultInstance().getAbout();
        onChanged();
        return this;
      }
      void setAbout(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        about_ = value;
        onChanged();
      }
      
      // optional string label = 3;
      private java.lang.Object label_ = "";
      public boolean hasLabel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLabel(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        label_ = value;
        onChanged();
        return this;
      }
      public Builder clearLabel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      void setLabel(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        label_ = value;
        onChanged();
      }
      
      // optional string length = 4;
      private java.lang.Object length_ = "";
      public boolean hasLength() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getLength() {
        java.lang.Object ref = length_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          length_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLength(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        length_ = value;
        onChanged();
        return this;
      }
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000008);
        length_ = getDefaultInstance().getLength();
        onChanged();
        return this;
      }
      void setLength(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        length_ = value;
        onChanged();
      }
      
      // optional string polyline = 5;
      private java.lang.Object polyline_ = "";
      public boolean hasPolyline() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getPolyline() {
        java.lang.Object ref = polyline_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          polyline_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPolyline(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        polyline_ = value;
        onChanged();
        return this;
      }
      public Builder clearPolyline() {
        bitField0_ = (bitField0_ & ~0x00000010);
        polyline_ = getDefaultInstance().getPolyline();
        onChanged();
        return this;
      }
      void setPolyline(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        polyline_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:eu.trentorise.smartcampus.service.trentinotrack.data.message.BikeTrack)
    }
    
    static {
      defaultInstance = new BikeTrack(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:eu.trentorise.smartcampus.service.trentinotrack.data.message.BikeTrack)
  }
  
  public interface OpenDataResourcePageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string link = 1;
    boolean hasLink();
    String getLink();
    
    // required string format = 2;
    boolean hasFormat();
    String getFormat();
  }
  public static final class OpenDataResourcePage extends
      com.google.protobuf.GeneratedMessage
      implements OpenDataResourcePageOrBuilder {
    // Use OpenDataResourcePage.newBuilder() to construct.
    private OpenDataResourcePage(Builder builder) {
      super(builder);
    }
    private OpenDataResourcePage(boolean noInit) {}
    
    private static final OpenDataResourcePage defaultInstance;
    public static OpenDataResourcePage getDefaultInstance() {
      return defaultInstance;
    }
    
    public OpenDataResourcePage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_OpenDataResourcePage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_OpenDataResourcePage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string link = 1;
    public static final int LINK_FIELD_NUMBER = 1;
    private java.lang.Object link_;
    public boolean hasLink() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getLink() {
      java.lang.Object ref = link_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          link_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLinkBytes() {
      java.lang.Object ref = link_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        link_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string format = 2;
    public static final int FORMAT_FIELD_NUMBER = 2;
    private java.lang.Object format_;
    public boolean hasFormat() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getFormat() {
      java.lang.Object ref = format_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          format_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFormatBytes() {
      java.lang.Object ref = format_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        format_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      link_ = "";
      format_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasLink()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFormat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getLinkBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFormatBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getLinkBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFormatBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_OpenDataResourcePage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_OpenDataResourcePage_fieldAccessorTable;
      }
      
      // Construct using eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        link_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        format_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage.getDescriptor();
      }
      
      public eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage getDefaultInstanceForType() {
        return eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage.getDefaultInstance();
      }
      
      public eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage build() {
        eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage buildPartial() {
        eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage result = new eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.link_ = link_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.format_ = format_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage) {
          return mergeFrom((eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage other) {
        if (other == eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage.getDefaultInstance()) return this;
        if (other.hasLink()) {
          setLink(other.getLink());
        }
        if (other.hasFormat()) {
          setFormat(other.getFormat());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasLink()) {
          
          return false;
        }
        if (!hasFormat()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              link_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              format_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string link = 1;
      private java.lang.Object link_ = "";
      public boolean hasLink() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getLink() {
        java.lang.Object ref = link_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          link_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLink(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        link_ = value;
        onChanged();
        return this;
      }
      public Builder clearLink() {
        bitField0_ = (bitField0_ & ~0x00000001);
        link_ = getDefaultInstance().getLink();
        onChanged();
        return this;
      }
      void setLink(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        link_ = value;
        onChanged();
      }
      
      // required string format = 2;
      private java.lang.Object format_ = "";
      public boolean hasFormat() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getFormat() {
        java.lang.Object ref = format_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          format_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFormat(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        format_ = value;
        onChanged();
        return this;
      }
      public Builder clearFormat() {
        bitField0_ = (bitField0_ & ~0x00000002);
        format_ = getDefaultInstance().getFormat();
        onChanged();
        return this;
      }
      void setFormat(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        format_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:eu.trentorise.smartcampus.service.trentinotrack.data.message.OpenDataResourcePage)
    }
    
    static {
      defaultInstance = new OpenDataResourcePage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:eu.trentorise.smartcampus.service.trentinotrack.data.message.OpenDataResourcePage)
  }
  
  public interface OpenDataResourcePagesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .eu.trentorise.smartcampus.service.trentinotrack.data.message.OpenDataResourcePage pages = 1;
    java.util.List<eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage> 
        getPagesList();
    eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage getPages(int index);
    int getPagesCount();
    java.util.List<? extends eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePageOrBuilder> 
        getPagesOrBuilderList();
    eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePageOrBuilder getPagesOrBuilder(
        int index);
  }
  public static final class OpenDataResourcePages extends
      com.google.protobuf.GeneratedMessage
      implements OpenDataResourcePagesOrBuilder {
    // Use OpenDataResourcePages.newBuilder() to construct.
    private OpenDataResourcePages(Builder builder) {
      super(builder);
    }
    private OpenDataResourcePages(boolean noInit) {}
    
    private static final OpenDataResourcePages defaultInstance;
    public static OpenDataResourcePages getDefaultInstance() {
      return defaultInstance;
    }
    
    public OpenDataResourcePages getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_OpenDataResourcePages_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_OpenDataResourcePages_fieldAccessorTable;
    }
    
    // repeated .eu.trentorise.smartcampus.service.trentinotrack.data.message.OpenDataResourcePage pages = 1;
    public static final int PAGES_FIELD_NUMBER = 1;
    private java.util.List<eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage> pages_;
    public java.util.List<eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage> getPagesList() {
      return pages_;
    }
    public java.util.List<? extends eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePageOrBuilder> 
        getPagesOrBuilderList() {
      return pages_;
    }
    public int getPagesCount() {
      return pages_.size();
    }
    public eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage getPages(int index) {
      return pages_.get(index);
    }
    public eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePageOrBuilder getPagesOrBuilder(
        int index) {
      return pages_.get(index);
    }
    
    private void initFields() {
      pages_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getPagesCount(); i++) {
        if (!getPages(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < pages_.size(); i++) {
        output.writeMessage(1, pages_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < pages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, pages_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePagesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_OpenDataResourcePages_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_OpenDataResourcePages_fieldAccessorTable;
      }
      
      // Construct using eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPagesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (pagesBuilder_ == null) {
          pages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          pagesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages.getDescriptor();
      }
      
      public eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages getDefaultInstanceForType() {
        return eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages.getDefaultInstance();
      }
      
      public eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages build() {
        eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages buildPartial() {
        eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages result = new eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages(this);
        int from_bitField0_ = bitField0_;
        if (pagesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            pages_ = java.util.Collections.unmodifiableList(pages_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.pages_ = pages_;
        } else {
          result.pages_ = pagesBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages) {
          return mergeFrom((eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages other) {
        if (other == eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages.getDefaultInstance()) return this;
        if (pagesBuilder_ == null) {
          if (!other.pages_.isEmpty()) {
            if (pages_.isEmpty()) {
              pages_ = other.pages_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePagesIsMutable();
              pages_.addAll(other.pages_);
            }
            onChanged();
          }
        } else {
          if (!other.pages_.isEmpty()) {
            if (pagesBuilder_.isEmpty()) {
              pagesBuilder_.dispose();
              pagesBuilder_ = null;
              pages_ = other.pages_;
              bitField0_ = (bitField0_ & ~0x00000001);
              pagesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPagesFieldBuilder() : null;
            } else {
              pagesBuilder_.addAllMessages(other.pages_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getPagesCount(); i++) {
          if (!getPages(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage.Builder subBuilder = eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPages(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .eu.trentorise.smartcampus.service.trentinotrack.data.message.OpenDataResourcePage pages = 1;
      private java.util.List<eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage> pages_ =
        java.util.Collections.emptyList();
      private void ensurePagesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          pages_ = new java.util.ArrayList<eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage>(pages_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage, eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage.Builder, eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePageOrBuilder> pagesBuilder_;
      
      public java.util.List<eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage> getPagesList() {
        if (pagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(pages_);
        } else {
          return pagesBuilder_.getMessageList();
        }
      }
      public int getPagesCount() {
        if (pagesBuilder_ == null) {
          return pages_.size();
        } else {
          return pagesBuilder_.getCount();
        }
      }
      public eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage getPages(int index) {
        if (pagesBuilder_ == null) {
          return pages_.get(index);
        } else {
          return pagesBuilder_.getMessage(index);
        }
      }
      public Builder setPages(
          int index, eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage value) {
        if (pagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePagesIsMutable();
          pages_.set(index, value);
          onChanged();
        } else {
          pagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setPages(
          int index, eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage.Builder builderForValue) {
        if (pagesBuilder_ == null) {
          ensurePagesIsMutable();
          pages_.set(index, builderForValue.build());
          onChanged();
        } else {
          pagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addPages(eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage value) {
        if (pagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePagesIsMutable();
          pages_.add(value);
          onChanged();
        } else {
          pagesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addPages(
          int index, eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage value) {
        if (pagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePagesIsMutable();
          pages_.add(index, value);
          onChanged();
        } else {
          pagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addPages(
          eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage.Builder builderForValue) {
        if (pagesBuilder_ == null) {
          ensurePagesIsMutable();
          pages_.add(builderForValue.build());
          onChanged();
        } else {
          pagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addPages(
          int index, eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage.Builder builderForValue) {
        if (pagesBuilder_ == null) {
          ensurePagesIsMutable();
          pages_.add(index, builderForValue.build());
          onChanged();
        } else {
          pagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllPages(
          java.lang.Iterable<? extends eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage> values) {
        if (pagesBuilder_ == null) {
          ensurePagesIsMutable();
          super.addAll(values, pages_);
          onChanged();
        } else {
          pagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearPages() {
        if (pagesBuilder_ == null) {
          pages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          pagesBuilder_.clear();
        }
        return this;
      }
      public Builder removePages(int index) {
        if (pagesBuilder_ == null) {
          ensurePagesIsMutable();
          pages_.remove(index);
          onChanged();
        } else {
          pagesBuilder_.remove(index);
        }
        return this;
      }
      public eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage.Builder getPagesBuilder(
          int index) {
        return getPagesFieldBuilder().getBuilder(index);
      }
      public eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePageOrBuilder getPagesOrBuilder(
          int index) {
        if (pagesBuilder_ == null) {
          return pages_.get(index);  } else {
          return pagesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePageOrBuilder> 
           getPagesOrBuilderList() {
        if (pagesBuilder_ != null) {
          return pagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(pages_);
        }
      }
      public eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage.Builder addPagesBuilder() {
        return getPagesFieldBuilder().addBuilder(
            eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage.getDefaultInstance());
      }
      public eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage.Builder addPagesBuilder(
          int index) {
        return getPagesFieldBuilder().addBuilder(
            index, eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage.getDefaultInstance());
      }
      public java.util.List<eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage.Builder> 
           getPagesBuilderList() {
        return getPagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage, eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage.Builder, eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePageOrBuilder> 
          getPagesFieldBuilder() {
        if (pagesBuilder_ == null) {
          pagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage, eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage.Builder, eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePageOrBuilder>(
                  pages_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          pages_ = null;
        }
        return pagesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:eu.trentorise.smartcampus.service.trentinotrack.data.message.OpenDataResourcePages)
    }
    
    static {
      defaultInstance = new OpenDataResourcePages(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:eu.trentorise.smartcampus.service.trentinotrack.data.message.OpenDataResourcePages)
  }
  
  public interface ResourceDescrOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string link = 1;
    boolean hasLink();
    String getLink();
    
    // optional string extPage = 2;
    boolean hasExtPage();
    String getExtPage();
  }
  public static final class ResourceDescr extends
      com.google.protobuf.GeneratedMessage
      implements ResourceDescrOrBuilder {
    // Use ResourceDescr.newBuilder() to construct.
    private ResourceDescr(Builder builder) {
      super(builder);
    }
    private ResourceDescr(boolean noInit) {}
    
    private static final ResourceDescr defaultInstance;
    public static ResourceDescr getDefaultInstance() {
      return defaultInstance;
    }
    
    public ResourceDescr getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_ResourceDescr_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_ResourceDescr_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string link = 1;
    public static final int LINK_FIELD_NUMBER = 1;
    private java.lang.Object link_;
    public boolean hasLink() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getLink() {
      java.lang.Object ref = link_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          link_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLinkBytes() {
      java.lang.Object ref = link_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        link_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string extPage = 2;
    public static final int EXTPAGE_FIELD_NUMBER = 2;
    private java.lang.Object extPage_;
    public boolean hasExtPage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getExtPage() {
      java.lang.Object ref = extPage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          extPage_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getExtPageBytes() {
      java.lang.Object ref = extPage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        extPage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      link_ = "";
      extPage_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasLink()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getLinkBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getExtPageBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getLinkBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getExtPageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescrOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_ResourceDescr_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_ResourceDescr_fieldAccessorTable;
      }
      
      // Construct using eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        link_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        extPage_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr.getDescriptor();
      }
      
      public eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr getDefaultInstanceForType() {
        return eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr.getDefaultInstance();
      }
      
      public eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr build() {
        eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr buildPartial() {
        eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr result = new eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.link_ = link_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.extPage_ = extPage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr) {
          return mergeFrom((eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr other) {
        if (other == eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr.getDefaultInstance()) return this;
        if (other.hasLink()) {
          setLink(other.getLink());
        }
        if (other.hasExtPage()) {
          setExtPage(other.getExtPage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasLink()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              link_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              extPage_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string link = 1;
      private java.lang.Object link_ = "";
      public boolean hasLink() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getLink() {
        java.lang.Object ref = link_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          link_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLink(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        link_ = value;
        onChanged();
        return this;
      }
      public Builder clearLink() {
        bitField0_ = (bitField0_ & ~0x00000001);
        link_ = getDefaultInstance().getLink();
        onChanged();
        return this;
      }
      void setLink(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        link_ = value;
        onChanged();
      }
      
      // optional string extPage = 2;
      private java.lang.Object extPage_ = "";
      public boolean hasExtPage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getExtPage() {
        java.lang.Object ref = extPage_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          extPage_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setExtPage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        extPage_ = value;
        onChanged();
        return this;
      }
      public Builder clearExtPage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        extPage_ = getDefaultInstance().getExtPage();
        onChanged();
        return this;
      }
      void setExtPage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        extPage_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:eu.trentorise.smartcampus.service.trentinotrack.data.message.ResourceDescr)
    }
    
    static {
      defaultInstance = new ResourceDescr(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:eu.trentorise.smartcampus.service.trentinotrack.data.message.ResourceDescr)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_BikeTrack_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_BikeTrack_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_OpenDataResourcePage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_OpenDataResourcePage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_OpenDataResourcePages_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_OpenDataResourcePages_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_ResourceDescr_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_ResourceDescr_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023trentinotrack.proto\022<eu.trentorise.sma" +
      "rtcampus.service.trentinotrack.data.mess" +
      "age\"W\n\tBikeTrack\022\n\n\002id\030\001 \002(\t\022\r\n\005about\030\002 " +
      "\002(\t\022\r\n\005label\030\003 \001(\t\022\016\n\006length\030\004 \001(\t\022\020\n\010po" +
      "lyline\030\005 \001(\t\"4\n\024OpenDataResourcePage\022\014\n\004" +
      "link\030\001 \002(\t\022\016\n\006format\030\002 \002(\t\"z\n\025OpenDataRe" +
      "sourcePages\022a\n\005pages\030\001 \003(\0132R.eu.trentori" +
      "se.smartcampus.service.trentinotrack.dat" +
      "a.message.OpenDataResourcePage\".\n\rResour" +
      "ceDescr\022\014\n\004link\030\001 \002(\t\022\017\n\007extPage\030\002 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_BikeTrack_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_BikeTrack_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_BikeTrack_descriptor,
              new java.lang.String[] { "Id", "About", "Label", "Length", "Polyline", },
              eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack.class,
              eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.BikeTrack.Builder.class);
          internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_OpenDataResourcePage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_OpenDataResourcePage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_OpenDataResourcePage_descriptor,
              new java.lang.String[] { "Link", "Format", },
              eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage.class,
              eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePage.Builder.class);
          internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_OpenDataResourcePages_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_OpenDataResourcePages_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_OpenDataResourcePages_descriptor,
              new java.lang.String[] { "Pages", },
              eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages.class,
              eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.OpenDataResourcePages.Builder.class);
          internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_ResourceDescr_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_ResourceDescr_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_trentorise_smartcampus_service_trentinotrack_data_message_ResourceDescr_descriptor,
              new java.lang.String[] { "Link", "ExtPage", },
              eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr.class,
              eu.trentorise.smartcampus.service.trentinotrack.data.message.Trentinotrack.ResourceDescr.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
